import { Inter } from "next/font/google";
import Header from "../../components/products/Header";
import SideBar from "../../components/products/SideBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProductLayout({ children }) {
  return (
    <div className="w-full bg-blue h-screen border dark:bg-zinc-800  dark:border-stone-400">
      <div className="h-[10%] ">
        <Header />
      </div>
      <div className="w-full flex h-[90%]">
        <div className="w-1/6 h-full border dark:bg-zinc-800 dark:border-stone-400">
          <SideBar />
        </div>
        <div className="w-5/6 h-full border dark:bg-zinc-800 dark:border-stone-400">
          {children}
        </div>
      </div>
    </div>
  );
}
